/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package frameworks;

import org.junit.Test;

import frameworks.lombok.model.Notes;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testNotesHasGeneratedMethods() {
    }
}
